### ISSUE TITLE
error NU1108: Cycle detected - when building project created from the template

### ISSUE THREAD

**Issue by theimowski** [SaturnFramework/Saturn.Template#7]
This one looks strange, like `saturn` would depend on itself...
Not sure if that's Paket related or not

1. `λ dotnet new Saturn --language F#`
2. `λ build`

```
...

Starting Target: Build (==> InstallDotNetCore)
dotnet "build" --configuration Release
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for C:\Users\BRE44821\sandbox\saturn\src\saturn\saturn.fsproj...
  Restore completed in 24.13 ms for C:\Users\BRE44821\sandbox\saturn\src\saturn\saturn.fsproj.
  Restore completed in 35.44 ms for C:\Users\BRE44821\sandbox\saturn\src\saturn\saturn.fsproj.
C:\Users\BRE44821\sandbox\saturn\src\saturn\saturn.fsproj : error NU1108: Cycle detected.
C:\Users\BRE44821\sandbox\saturn\src\saturn\saturn.fsproj : error NU1108:   saturn -> Saturn (>= 0.4.3).
  Generating MSBuild file C:\Users\BRE44821\sandbox\saturn\src\saturn\obj\saturn.fsproj.nuget.g.props.
  Restore failed in 643.02 ms for C:\Users\BRE44821\sandbox\saturn\src\saturn\saturn.fsproj.

Build FAILED.

C:\Users\BRE44821\sandbox\saturn\src\saturn\saturn.fsproj : error NU1108: Cycle detected.
C:\Users\BRE44821\sandbox\saturn\src\saturn\saturn.fsproj : error NU1108:   saturn -> Saturn (>= 0.4.3).
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.52
Running build failed.
Error:
System.Exception: Build failed on "build" --configuration Release
   at Fake.DotNetCli.Build@224-3.Invoke(String message) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 224
   at Fake.DotNetCli.Build(FSharpFunc`2 setBuildParams) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 224
   at FSI_0005.Build.clo@22-4.Invoke(Unit _arg3) in C:\Users\BRE44821\sandbox\saturn\build.fsx:line 23
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```

```
λ dotnet --version
2.1.4
```

```
λ dotnet new Saturn --help
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Specifies the language of the template to create.


Saturn v0.4.1 (F#)
Author: Krzysztof Cieslak
    (No Parameters)
```

**Comment by theimowski** [comment]
This is related to https://github.com/dotnet/cli/issues/3508 and https://github.com/NuGet/Home/issues/1428

Seems that this happens when not specifying `--name` parameter to `dotnet new`.
Without `--name` parameter, *"The name for the output being created. If no name is specified, the name of the current directory is used."*, resulting in following structure (assuming current dir is named `saturn`:


```
saturn
└───src
    ├───Migrations
    │      ...
    └───saturn
        │  ....
        │   saturn.fsproj
        │...
```

and then for some reason NuGet can't resolve deps because of cycle

As a workaround I had to give `--name` explicitly using different name than current directory.

**Comment by philcarbone** [comment]
The issue pops up if you are referencing a package from a folder that CONTAINS the same name too. For instance a package called My.Special.Code  can't be reference in a folder called My.Special.Code.ForServices otherwise it will get the same error:   Cycle detected. My.Special.Code -> My.Special.Code

This is what we've seen and this is a huge problem.

**Comment by Krzysztof-Cieslak** [comment]
It's nothing really specific to Saturn, that's just how NuGet and MsBuild works. I've merged @theimowski PR that adds info about it to readme.
